//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.1
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrderFormSystem.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OrderFormSystem.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 添加助剂失败 的本地化字符串。
        /// </summary>
        internal static string AddAuxiliaryError {
            get {
                return ResourceManager.GetString("AddAuxiliaryError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 添加染料失败 的本地化字符串。
        /// </summary>
        internal static string AddDyeError {
            get {
                return ResourceManager.GetString("AddDyeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 清除助剂失败 的本地化字符串。
        /// </summary>
        internal static string ClearAuxiliaryError {
            get {
                return ResourceManager.GetString("ClearAuxiliaryError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 清除染料失败 的本地化字符串。
        /// </summary>
        internal static string ClearDyeError {
            get {
                return ResourceManager.GetString("ClearDyeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 代码不能为空 的本地化字符串。
        /// </summary>
        internal static string CodeInputError {
            get {
                return ResourceManager.GetString("CodeInputError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 色号不能为空 的本地化字符串。
        /// </summary>
        internal static string ColorNumberEmpty {
            get {
                return ResourceManager.GetString("ColorNumberEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 连接成功 的本地化字符串。
        /// </summary>
        internal static string ConnectSuccess {
            get {
                return ResourceManager.GetString("ConnectSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 创建订单失败 的本地化字符串。
        /// </summary>
        internal static string CreateOrderFailed {
            get {
                return ResourceManager.GetString("CreateOrderFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 筒子个数值输入非法 的本地化字符串。
        /// </summary>
        internal static string CreelCountError {
            get {
                return ResourceManager.GetString("CreelCountError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 删除助剂失败 的本地化字符串。
        /// </summary>
        internal static string DelAuxiliaryError {
            get {
                return ResourceManager.GetString("DelAuxiliaryError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 删除染料失败 的本地化字符串。
        /// </summary>
        internal static string DelDyeError {
            get {
                return ResourceManager.GetString("DelDyeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 密度值输入错误 的本地化字符串。
        /// </summary>
        internal static string DensityError {
            get {
                return ResourceManager.GetString("DensityError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 密度值非法,请输入正确数值 的本地化字符串。
        /// </summary>
        internal static string DensityInputError {
            get {
                return ResourceManager.GetString("DensityInputError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 染助剂代码输入错误 的本地化字符串。
        /// </summary>
        internal static string DyeCodeInputError {
            get {
                return ResourceManager.GetString("DyeCodeInputError", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap eWeight {
            get {
                object obj = ResourceManager.GetObject("eWeight", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap libra {
            get {
                object obj = ResourceManager.GetObject("libra", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 浴比值输入非法 的本地化字符串。
        /// </summary>
        internal static string LiquorRatioError {
            get {
                return ResourceManager.GetString("LiquorRatioError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 没有这个用户,请输入正确用户名 的本地化字符串。
        /// </summary>
        internal static string LoginNoName {
            get {
                return ResourceManager.GetString("LoginNoName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 密码错误,请输入正确密码! 的本地化字符串。
        /// </summary>
        internal static string LoginPasswordError {
            get {
                return ResourceManager.GetString("LoginPasswordError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 配方太过复杂了 的本地化字符串。
        /// </summary>
        internal static string LongPrescriptionError {
            get {
                return ResourceManager.GetString("LongPrescriptionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 机器 代号不能为空 的本地化字符串。
        /// </summary>
        internal static string MachineCode {
            get {
                return ResourceManager.GetString("MachineCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 名字不能为空 的本地化字符串。
        /// </summary>
        internal static string NameInputError {
            get {
                return ResourceManager.GetString("NameInputError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 含有非法字符,请输入数字值 的本地化字符串。
        /// </summary>
        internal static string NumberInputError {
            get {
                return ResourceManager.GetString("NumberInputError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 订单号不能为空 的本地化字符串。
        /// </summary>
        internal static string OrderIDEmpty {
            get {
                return ResourceManager.GetString("OrderIDEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 已经加入传送队列中 的本地化字符串。
        /// </summary>
        internal static string OrderIDViewAdded {
            get {
                return ResourceManager.GetString("OrderIDViewAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 删除订单号失败 的本地化字符串。
        /// </summary>
        internal static string OrderIDViewDeleteFailed {
            get {
                return ResourceManager.GetString("OrderIDViewDeleteFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 没有选中订单号 的本地化字符串。
        /// </summary>
        internal static string OrderIDViewNoSelected {
            get {
                return ResourceManager.GetString("OrderIDViewNoSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 订单传送失败 的本地化字符串。
        /// </summary>
        internal static string OrderSendFailed {
            get {
                return ResourceManager.GetString("OrderSendFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 订单传送成功 的本地化字符串。
        /// </summary>
        internal static string OrderSendSuccess {
            get {
                return ResourceManager.GetString("OrderSendSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 两次输入密码不一致,请重新输入 的本地化字符串。
        /// </summary>
        internal static string PasswdDiff {
            get {
                return ResourceManager.GetString("PasswdDiff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 花色不能为空 的本地化字符串。
        /// </summary>
        internal static string PatternEmpty {
            get {
                return ResourceManager.GetString("PatternEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 配方值不能为空 的本地化字符串。
        /// </summary>
        internal static string PrescriptionEmpty {
            get {
                return ResourceManager.GetString("PrescriptionEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 修改密码成功! 的本地化字符串。
        /// </summary>
        internal static string PwdChanged {
            get {
                return ResourceManager.GetString("PwdChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 数据库未知错误,修改密码失败,将继续使用原来的密码! 的本地化字符串。
        /// </summary>
        internal static string PwdChangeFailed {
            get {
                return ResourceManager.GetString("PwdChangeFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 注册失败,请输入正确的注册码! 的本地化字符串。
        /// </summary>
        internal static string RegisterFailed {
            get {
                return ResourceManager.GetString("RegisterFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 软件注册成功! 的本地化字符串。
        /// </summary>
        internal static string RegisterSuccess {
            get {
                return ResourceManager.GetString("RegisterSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 订单存档失败 的本地化字符串。
        /// </summary>
        internal static string SaveOrderFailed {
            get {
                return ResourceManager.GetString("SaveOrderFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 订单存档成功 的本地化字符串。
        /// </summary>
        internal static string SaveOrderSuccess {
            get {
                return ResourceManager.GetString("SaveOrderSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 生产步骤格式不对 的本地化字符串。
        /// </summary>
        internal static string StepCountError {
            get {
                return ResourceManager.GetString("StepCountError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 存单时间异常 的本地化字符串。
        /// </summary>
        internal static string StoreTimeEmpty {
            get {
                return ResourceManager.GetString("StoreTimeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 更新失败 的本地化字符串。
        /// </summary>
        internal static string UpdateError {
            get {
                return ResourceManager.GetString("UpdateError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 添加用户成功! 的本地化字符串。
        /// </summary>
        internal static string UserAdded {
            get {
                return ResourceManager.GetString("UserAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 成功删除用户 的本地化字符串。
        /// </summary>
        internal static string UserDeleted {
            get {
                return ResourceManager.GetString("UserDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 添加用户失败 的本地化字符串。
        /// </summary>
        internal static string UserUnAdd {
            get {
                return ResourceManager.GetString("UserUnAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 阀号值非法,请输入整数的阀号 的本地化字符串。
        /// </summary>
        internal static string ValveInputError {
            get {
                return ResourceManager.GetString("ValveInputError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 阀号不能不写 的本地化字符串。
        /// </summary>
        internal static string ValveInputNull {
            get {
                return ResourceManager.GetString("ValveInputNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 水位值输入错误 的本地化字符串。
        /// </summary>
        internal static string WaterWeightError {
            get {
                return ResourceManager.GetString("WaterWeightError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 纱支值输入非法 的本地化字符串。
        /// </summary>
        internal static string YarnCountError {
            get {
                return ResourceManager.GetString("YarnCountError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 纱重值输入非法 的本地化字符串。
        /// </summary>
        internal static string YarnWeightError {
            get {
                return ResourceManager.GetString("YarnWeightError", resourceCulture);
            }
        }
    }
}
